apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-and-sign
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/km-build-and-sign/build-and-sign@sha256:d3d946d2177f8c9c7b56c8187dcf6d348d2cad407a4eb0423a4e7c55da165e99
        name: container-image
        resources: {}
status: {}
