apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-and-sign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-and-sign
    app.kubernetes.io/part-of: km-build-and-sign
  name: build-and-signzo23
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: build-and-sign
    weight: 100
status: {}
