apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-and-sign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-and-sign
    app.kubernetes.io/part-of: km-build-and-sign
  name: build-and-sign
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-and-sign
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-and-sign
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/km-build-and-sign/build-and-sign@sha256:62c2ac5657e670d7a55e5e4fe790750629ca7595489c009ee41507cb4d5ba408
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
