apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-and-sign
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-and-sign
    app.kubernetes.io/part-of: km-build-and-sign
  name: build-and-sign
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: build-and-sign
status:
  loadBalancer: {}
